all:
  children:
    postgresql:
      hosts:
        postgresql.postgresql.svc.cluster.local:
          ansible_connection: local
          pg_environment: producao
          vault_secret: postgresql-prod
